"""
Contratos (ports) que a camada de aplicação depende e a infraestrutura
implementa — mesmo princípio de inversão de dependência das outras duas
APIs, só que expresso com typing.Protocol (structural typing) em vez de
interface/ABC: em Python isso é o suficiente e é o jeito idiomático de
declarar "qualquer coisa com esse formato serve", sem herança obrigatória.
"""
from __future__ import annotations

from typing import Any, Optional, Protocol

from app.domain.models import Client, Order, Payment, Product, Stock


class ClientRepository(Protocol):
    async def create(self, client: Client) -> Client: ...
    async def get_by_id(self, client_id: str) -> Optional[Client]: ...
    async def list_all(self) -> list[Client]: ...
    async def update(self, client: Client) -> Client: ...
    async def delete(self, client_id: str) -> None: ...


class ProductRepository(Protocol):
    async def create(self, product: Product) -> Product: ...
    async def get_by_id(self, product_id: str) -> Optional[Product]: ...
    async def get_by_sku(self, sku: str) -> Optional[Product]: ...
    async def list_all(self) -> list[Product]: ...
    async def update(self, product: Product) -> Product: ...
    async def delete(self, product_id: str) -> None: ...


class StockRepository(Protocol):
    async def create(self, stock: Stock) -> Stock: ...
    async def get_by_id(self, product_id: str) -> Optional[Stock]: ...
    async def list_all(self) -> list[Stock]: ...
    async def update(self, stock: Stock) -> Stock: ...
    async def delete(self, product_id: str) -> None: ...


class OrderRepository(Protocol):
    async def create(self, order: Order) -> Order: ...
    async def get_by_id(self, order_id: str) -> Optional[Order]: ...
    async def list_all(self) -> list[Order]: ...
    async def update(self, order: Order) -> Order: ...
    async def delete(self, order_id: str) -> None: ...


class PaymentRepository(Protocol):
    async def create(self, payment: Payment) -> Payment: ...
    async def get_by_id(self, payment_id: str) -> Optional[Payment]: ...
    async def update(self, payment: Payment) -> Payment: ...


class UnitOfWork(Protocol):
    """
    Equivalente ao UnitOfWorkRepository do Java/NestJS, mas expresso como
    async context manager — o jeito Python de dizer "abre e fecha um
    recurso": `async with uow: ...`. __aexit__ dá rollback automático se
    uma exceção escapar do bloco; commit() é sempre explícito.
    """

    orders: OrderRepository
    stocks: StockRepository
    payments: PaymentRepository

    async def __aenter__(self) -> "UnitOfWork": ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class PaymentGateway(Protocol):
    async def create_charge(self, payment_id: str, order_id: str, amount: float, idempotency_key: str) -> dict[str, Any]: ...
    async def retrieve_charge(self, idempotency_key: str) -> dict[str, Any]: ...


class CacheStore(Protocol):
    async def get(self, key: str) -> Optional[dict]: ...
    async def set(self, key: str, value: dict, ttl_seconds: int) -> None: ...
    async def delete(self, key: str) -> None: ...


class IdempotencyStore(Protocol):
    async def try_start(self, key: str, ttl_seconds: int) -> bool: ...
    async def get(self, key: str) -> Optional[dict]: ...
    async def complete(self, key: str, status_code: int, body: Any, ttl_seconds: int) -> None: ...
    async def release(self, key: str) -> None: ...
