spring.application.name=order

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/api_spring_distributed_order_platform
spring.datasource.username=postgres
spring.datasource.password=123456

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Redis (cache de leitura + Idempotency-Key), ver docker-compose.yml na raiz do projeto
spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=3020

